server:
  port: 8087

spring:
  profiles:
    active: production
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        legacy_limit_handler: true
        proc:
          param_null_passing: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.tigo.com.gt
    port: 25
    properties:
      mail:
        smtp:
          auth: false
---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    application:
      jndi-name: jdbc/orquestador-network
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.trace: debug
    gt.com.tigo: debug
azure:
  application:
    id: 630b2ebb-fcb9-47b7-b8a1-027518bc7154
    callback-url: http://localhost:3000
log4j:
  logger:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---

spring:
  config:
    activate:
      on-profile: development-alt
  datasource:
    application:
      jndi-name: jdbc/orquestador-network
logging:
  level:
    org.hibernate.SQL: debug
    gt.com.tigo: debug
azure:
  application:
    id: 73893002-7fcb-4735-b02a-627fffe7201b
    callback-url: http://localhost:3100

---

spring:
  config:
    activate:
      on-profile: test-remote
  datasource:
    application:
      jndi-name: jdbc/orquestador-network
logging:
  level:
    org.hibernate.SQL: debug
    gt.com.tigo: debug
azure:
  application:
    id: f1f68aaa-ea6e-455e-bf8c-993fb3c399f8
    callback-url: https://corporateappsdev.tigo.com.gt/orquestador-network/

---


spring:
  config:
    activate:
      on-profile: qa
  datasource:
    application:
      jndi-name: jdbc/orquestador-network
logging:
  level:
    org.hibernate.SQL: debug
    gt.com.tigo: debug
azure:
  application:
    id: 31bc8a65-de04-4d97-939e-811f3d2ece8d
    callback-url: https://corporateappsqa.tigo.com.gt/orquestador-network/

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    application:
      jndi-name: jdbc/orquestador-network
logging:
  level:
    org.hibernate.SQL: debug
    gt.com.tigo: debug
azure:
  application:
    id: 31bc8a65-de04-4d97-939e-811f3d2ece8d
    callback-url: https://corporateapps.tigo.com.gt/orquestador-network/